"use strict";
// Code generated by protoc-gen-tsrpc DO NOT EDIT.
// InputID: f5d34f9844bb28020b0b444e9c8338b0bc4bd042
var __createBinding = (this && this.__createBinding) || (Object.create ? (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    Object.defineProperty(o, k2, { enumerable: true, get: function() { return m[k]; } });
}) : (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    o[k2] = m[k];
}));
var __setModuleDefault = (this && this.__setModuleDefault) || (Object.create ? (function(o, v) {
    Object.defineProperty(o, "default", { enumerable: true, value: v });
}) : function(o, v) {
    o["default"] = v;
});
var __importStar = (this && this.__importStar) || function (mod) {
    if (mod && mod.__esModule) return mod;
    var result = {};
    if (mod != null) for (var k in mod) if (k !== "default" && Object.prototype.hasOwnProperty.call(mod, k)) __createBinding(result, mod, k);
    __setModuleDefault(result, mod);
    return result;
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.RPCService = void 0;
const grpc = __importStar(require("@grpc/grpc-js"));
const events_1 = require("events");
const ts_log_1 = require("ts-log");
class RPCService extends events_1.EventEmitter {
    constructor(serviceFn) {
        super();
        this.log = ts_log_1.dummyLogger;
        this.serviceFn = serviceFn;
    }
    service() {
        if (!this.client) {
            this.client = this.serviceFn();
        }
        return this.client;
    }
    emitError(err) {
        switch (err.code) {
            case grpc.status.PERMISSION_DENIED:
            case grpc.status.UNAUTHENTICATED:
                this.emit('unauthenticated', err);
                break;
            case grpc.status.UNAVAILABLE:
                this.emit('unavailable', err);
                break;
            default:
                this.emit('error', err);
                break;
        }
    }
    authStatus(req) {
        return new Promise((resolve, reject) => {
            this.log.info('authStatus');
            this.service().authStatus(req, (err, resp) => {
                if (err) {
                    reject(err);
                    this.emitError(err);
                    return;
                }
                resolve(resp);
            });
        });
    }
    authUnlock(req) {
        return new Promise((resolve, reject) => {
            this.log.info('authUnlock');
            this.service().authUnlock(req, (err, resp) => {
                if (err) {
                    reject(err);
                    this.emitError(err);
                    return;
                }
                resolve(resp);
            });
        });
    }
    authLock(req) {
        return new Promise((resolve, reject) => {
            this.log.info('authLock');
            this.service().authLock(req, (err, resp) => {
                if (err) {
                    reject(err);
                    this.emitError(err);
                    return;
                }
                resolve(resp);
            });
        });
    }
    rand(req) {
        return new Promise((resolve, reject) => {
            this.log.info('rand');
            this.service().rand(req, (err, resp) => {
                if (err) {
                    reject(err);
                    this.emitError(err);
                    return;
                }
                resolve(resp);
            });
        });
    }
    randPassword(req) {
        return new Promise((resolve, reject) => {
            this.log.info('randPassword');
            this.service().randPassword(req, (err, resp) => {
                if (err) {
                    reject(err);
                    this.emitError(err);
                    return;
                }
                resolve(resp);
            });
        });
    }
    accountRegister(req) {
        return new Promise((resolve, reject) => {
            this.log.info('accountRegister');
            this.service().accountRegister(req, (err, resp) => {
                if (err) {
                    reject(err);
                    this.emitError(err);
                    return;
                }
                resolve(resp);
            });
        });
    }
    accountCreate(req) {
        return new Promise((resolve, reject) => {
            this.log.info('accountCreate');
            this.service().accountCreate(req, (err, resp) => {
                if (err) {
                    reject(err);
                    this.emitError(err);
                    return;
                }
                resolve(resp);
            });
        });
    }
    accountStatus(req) {
        return new Promise((resolve, reject) => {
            this.log.info('accountStatus');
            this.service().accountStatus(req, (err, resp) => {
                if (err) {
                    reject(err);
                    this.emitError(err);
                    return;
                }
                resolve(resp);
            });
        });
    }
    accountSetUsername(req) {
        return new Promise((resolve, reject) => {
            this.log.info('accountSetUsername');
            this.service().accountSetUsername(req, (err, resp) => {
                if (err) {
                    reject(err);
                    this.emitError(err);
                    return;
                }
                resolve(resp);
            });
        });
    }
    keyGenerate(req) {
        return new Promise((resolve, reject) => {
            this.log.info('keyGenerate');
            this.service().keyGenerate(req, (err, resp) => {
                if (err) {
                    reject(err);
                    this.emitError(err);
                    return;
                }
                resolve(resp);
            });
        });
    }
    keys(req) {
        return new Promise((resolve, reject) => {
            this.log.info('keys');
            this.service().keys(req, (err, resp) => {
                if (err) {
                    reject(err);
                    this.emitError(err);
                    return;
                }
                resolve(resp);
            });
        });
    }
    key(req) {
        return new Promise((resolve, reject) => {
            this.log.info('key');
            this.service().key(req, (err, resp) => {
                if (err) {
                    reject(err);
                    this.emitError(err);
                    return;
                }
                resolve(resp);
            });
        });
    }
    keyImport(req) {
        return new Promise((resolve, reject) => {
            this.log.info('keyImport');
            this.service().keyImport(req, (err, resp) => {
                if (err) {
                    reject(err);
                    this.emitError(err);
                    return;
                }
                resolve(resp);
            });
        });
    }
    keyExport(req) {
        return new Promise((resolve, reject) => {
            this.log.info('keyExport');
            this.service().keyExport(req, (err, resp) => {
                if (err) {
                    reject(err);
                    this.emitError(err);
                    return;
                }
                resolve(resp);
            });
        });
    }
    keyRemove(req) {
        return new Promise((resolve, reject) => {
            this.log.info('keyRemove');
            this.service().keyRemove(req, (err, resp) => {
                if (err) {
                    reject(err);
                    this.emitError(err);
                    return;
                }
                resolve(resp);
            });
        });
    }
    keySearch(req) {
        return new Promise((resolve, reject) => {
            this.log.info('keySearch');
            this.service().keySearch(req, (err, resp) => {
                if (err) {
                    reject(err);
                    this.emitError(err);
                    return;
                }
                resolve(resp);
            });
        });
    }
    user(req) {
        return new Promise((resolve, reject) => {
            this.log.info('user');
            this.service().user(req, (err, resp) => {
                if (err) {
                    reject(err);
                    this.emitError(err);
                    return;
                }
                resolve(resp);
            });
        });
    }
    userSearch(req) {
        return new Promise((resolve, reject) => {
            this.log.info('userSearch');
            this.service().userSearch(req, (err, resp) => {
                if (err) {
                    reject(err);
                    this.emitError(err);
                    return;
                }
                resolve(resp);
            });
        });
    }
    userService(req) {
        return new Promise((resolve, reject) => {
            this.log.info('userService');
            this.service().userService(req, (err, resp) => {
                if (err) {
                    reject(err);
                    this.emitError(err);
                    return;
                }
                resolve(resp);
            });
        });
    }
    userSign(req) {
        return new Promise((resolve, reject) => {
            this.log.info('userSign');
            this.service().userSign(req, (err, resp) => {
                if (err) {
                    reject(err);
                    this.emitError(err);
                    return;
                }
                resolve(resp);
            });
        });
    }
    userAdd(req) {
        return new Promise((resolve, reject) => {
            this.log.info('userAdd');
            this.service().userAdd(req, (err, resp) => {
                if (err) {
                    reject(err);
                    this.emitError(err);
                    return;
                }
                resolve(resp);
            });
        });
    }
    pull(req) {
        return new Promise((resolve, reject) => {
            this.log.info('pull');
            this.service().pull(req, (err, resp) => {
                if (err) {
                    reject(err);
                    this.emitError(err);
                    return;
                }
                resolve(resp);
            });
        });
    }
    sigchain(req) {
        return new Promise((resolve, reject) => {
            this.log.info('sigchain');
            this.service().sigchain(req, (err, resp) => {
                if (err) {
                    reject(err);
                    this.emitError(err);
                    return;
                }
                resolve(resp);
            });
        });
    }
    statement(req) {
        return new Promise((resolve, reject) => {
            this.log.info('statement');
            this.service().statement(req, (err, resp) => {
                if (err) {
                    reject(err);
                    this.emitError(err);
                    return;
                }
                resolve(resp);
            });
        });
    }
    statementCreate(req) {
        return new Promise((resolve, reject) => {
            this.log.info('statementCreate');
            this.service().statementCreate(req, (err, resp) => {
                if (err) {
                    reject(err);
                    this.emitError(err);
                    return;
                }
                resolve(resp);
            });
        });
    }
    statementRevoke(req) {
        return new Promise((resolve, reject) => {
            this.log.info('statementRevoke');
            this.service().statementRevoke(req, (err, resp) => {
                if (err) {
                    reject(err);
                    this.emitError(err);
                    return;
                }
                resolve(resp);
            });
        });
    }
    channels(req) {
        return new Promise((resolve, reject) => {
            this.log.info('channels');
            this.service().channels(req, (err, resp) => {
                if (err) {
                    reject(err);
                    this.emitError(err);
                    return;
                }
                resolve(resp);
            });
        });
    }
    channelCreate(req) {
        return new Promise((resolve, reject) => {
            this.log.info('channelCreate');
            this.service().channelCreate(req, (err, resp) => {
                if (err) {
                    reject(err);
                    this.emitError(err);
                    return;
                }
                resolve(resp);
            });
        });
    }
    channelInvite(req) {
        return new Promise((resolve, reject) => {
            this.log.info('channelInvite');
            this.service().channelInvite(req, (err, resp) => {
                if (err) {
                    reject(err);
                    this.emitError(err);
                    return;
                }
                resolve(resp);
            });
        });
    }
    channelLeave(req) {
        return new Promise((resolve, reject) => {
            this.log.info('channelLeave');
            this.service().channelLeave(req, (err, resp) => {
                if (err) {
                    reject(err);
                    this.emitError(err);
                    return;
                }
                resolve(resp);
            });
        });
    }
    channelRead(req) {
        return new Promise((resolve, reject) => {
            this.log.info('channelRead');
            this.service().channelRead(req, (err, resp) => {
                if (err) {
                    reject(err);
                    this.emitError(err);
                    return;
                }
                resolve(resp);
            });
        });
    }
    messagePrepare(req) {
        return new Promise((resolve, reject) => {
            this.log.info('messagePrepare');
            this.service().messagePrepare(req, (err, resp) => {
                if (err) {
                    reject(err);
                    this.emitError(err);
                    return;
                }
                resolve(resp);
            });
        });
    }
    messageCreate(req) {
        return new Promise((resolve, reject) => {
            this.log.info('messageCreate');
            this.service().messageCreate(req, (err, resp) => {
                if (err) {
                    reject(err);
                    this.emitError(err);
                    return;
                }
                resolve(resp);
            });
        });
    }
    messages(req) {
        return new Promise((resolve, reject) => {
            this.log.info('messages');
            this.service().messages(req, (err, resp) => {
                if (err) {
                    reject(err);
                    this.emitError(err);
                    return;
                }
                resolve(resp);
            });
        });
    }
    relay(req) {
        this.log.info('relay');
        return this.service().relay(req);
    }
    collections(req) {
        return new Promise((resolve, reject) => {
            this.log.info('collections');
            this.service().collections(req, (err, resp) => {
                if (err) {
                    reject(err);
                    this.emitError(err);
                    return;
                }
                resolve(resp);
            });
        });
    }
    documents(req) {
        return new Promise((resolve, reject) => {
            this.log.info('documents');
            this.service().documents(req, (err, resp) => {
                if (err) {
                    reject(err);
                    this.emitError(err);
                    return;
                }
                resolve(resp);
            });
        });
    }
    teamInvites(req) {
        return new Promise((resolve, reject) => {
            this.log.info('teamInvites');
            this.service().teamInvites(req, (err, resp) => {
                if (err) {
                    reject(err);
                    this.emitError(err);
                    return;
                }
                resolve(resp);
            });
        });
    }
}
exports.RPCService = RPCService;
//# sourceMappingURL=rpc.service.js.map