"use strict";
// Code generated by protoc-gen-tsrpc DO NOT EDIT.
// InputID: e798e648faadc50b876320a6418ea89789423cb8
var __createBinding = (this && this.__createBinding) || (Object.create ? (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    Object.defineProperty(o, k2, { enumerable: true, get: function() { return m[k]; } });
}) : (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    o[k2] = m[k];
}));
var __setModuleDefault = (this && this.__setModuleDefault) || (Object.create ? (function(o, v) {
    Object.defineProperty(o, "default", { enumerable: true, value: v });
}) : function(o, v) {
    o["default"] = v;
});
var __importStar = (this && this.__importStar) || function (mod) {
    if (mod && mod.__esModule) return mod;
    var result = {};
    if (mod != null) for (var k in mod) if (k !== "default" && Object.prototype.hasOwnProperty.call(mod, k)) __createBinding(result, mod, k);
    __setModuleDefault(result, mod);
    return result;
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.RPCService = void 0;
const grpc = __importStar(require("@grpc/grpc-js"));
const events_1 = require("events");
const ts_log_1 = require("ts-log");
class RPCService extends events_1.EventEmitter {
    constructor(serviceFn) {
        super();
        this.log = ts_log_1.dummyLogger;
        this.serviceFn = serviceFn;
    }
    service() {
        if (!this.client) {
            this.client = this.serviceFn();
        }
        return this.client;
    }
    emitError(err) {
        switch (err.code) {
            case grpc.status.PERMISSION_DENIED:
            case grpc.status.UNAUTHENTICATED:
                this.emit('unauthenticated', err);
                break;
            case grpc.status.UNAVAILABLE:
                this.emit('unavailable', err);
                break;
            default:
                this.emit('error', err);
                break;
        }
    }
    authSetup(req) {
        return new Promise((resolve, reject) => {
            this.log.info('authSetup');
            this.service().authSetup(req, (err, resp) => {
                if (err) {
                    reject(err);
                    this.emitError(err);
                    return;
                }
                resolve(resp);
            });
        });
    }
    authUnlock(req) {
        return new Promise((resolve, reject) => {
            this.log.info('authUnlock');
            this.service().authUnlock(req, (err, resp) => {
                if (err) {
                    reject(err);
                    this.emitError(err);
                    return;
                }
                resolve(resp);
            });
        });
    }
    authLock(req) {
        return new Promise((resolve, reject) => {
            this.log.info('authLock');
            this.service().authLock(req, (err, resp) => {
                if (err) {
                    reject(err);
                    this.emitError(err);
                    return;
                }
                resolve(resp);
            });
        });
    }
    runtimeStatus(req) {
        return new Promise((resolve, reject) => {
            this.log.info('runtimeStatus');
            this.service().runtimeStatus(req, (err, resp) => {
                if (err) {
                    reject(err);
                    this.emitError(err);
                    return;
                }
                resolve(resp);
            });
        });
    }
    keyGenerate(req) {
        return new Promise((resolve, reject) => {
            this.log.info('keyGenerate');
            this.service().keyGenerate(req, (err, resp) => {
                if (err) {
                    reject(err);
                    this.emitError(err);
                    return;
                }
                resolve(resp);
            });
        });
    }
    keys(req) {
        return new Promise((resolve, reject) => {
            this.log.info('keys');
            this.service().keys(req, (err, resp) => {
                if (err) {
                    reject(err);
                    this.emitError(err);
                    return;
                }
                resolve(resp);
            });
        });
    }
    key(req) {
        return new Promise((resolve, reject) => {
            this.log.info('key');
            this.service().key(req, (err, resp) => {
                if (err) {
                    reject(err);
                    this.emitError(err);
                    return;
                }
                resolve(resp);
            });
        });
    }
    keyImport(req) {
        return new Promise((resolve, reject) => {
            this.log.info('keyImport');
            this.service().keyImport(req, (err, resp) => {
                if (err) {
                    reject(err);
                    this.emitError(err);
                    return;
                }
                resolve(resp);
            });
        });
    }
    keyExport(req) {
        return new Promise((resolve, reject) => {
            this.log.info('keyExport');
            this.service().keyExport(req, (err, resp) => {
                if (err) {
                    reject(err);
                    this.emitError(err);
                    return;
                }
                resolve(resp);
            });
        });
    }
    keyRemove(req) {
        return new Promise((resolve, reject) => {
            this.log.info('keyRemove');
            this.service().keyRemove(req, (err, resp) => {
                if (err) {
                    reject(err);
                    this.emitError(err);
                    return;
                }
                resolve(resp);
            });
        });
    }
    user(req) {
        return new Promise((resolve, reject) => {
            this.log.info('user');
            this.service().user(req, (err, resp) => {
                if (err) {
                    reject(err);
                    this.emitError(err);
                    return;
                }
                resolve(resp);
            });
        });
    }
    userSearch(req) {
        return new Promise((resolve, reject) => {
            this.log.info('userSearch');
            this.service().userSearch(req, (err, resp) => {
                if (err) {
                    reject(err);
                    this.emitError(err);
                    return;
                }
                resolve(resp);
            });
        });
    }
    userService(req) {
        return new Promise((resolve, reject) => {
            this.log.info('userService');
            this.service().userService(req, (err, resp) => {
                if (err) {
                    reject(err);
                    this.emitError(err);
                    return;
                }
                resolve(resp);
            });
        });
    }
    userSign(req) {
        return new Promise((resolve, reject) => {
            this.log.info('userSign');
            this.service().userSign(req, (err, resp) => {
                if (err) {
                    reject(err);
                    this.emitError(err);
                    return;
                }
                resolve(resp);
            });
        });
    }
    userAdd(req) {
        return new Promise((resolve, reject) => {
            this.log.info('userAdd');
            this.service().userAdd(req, (err, resp) => {
                if (err) {
                    reject(err);
                    this.emitError(err);
                    return;
                }
                resolve(resp);
            });
        });
    }
}
exports.RPCService = RPCService;
//# sourceMappingURL=rpc.service.js.map